### ISSUE TITLE
Entering shell commands duplicates them

### ISSUE THREAD

**Issue by PlanetWilson** [gogolith/gocoeditserver#11]
Whenever I SSH Into my server and enter something, pressing return seems to duplicate the whole line again first then act upon the return key. Using v8.4 on iPad Pro 9.7

**Comment by gogolith** [comment]
Hi PlanetWilson, thank you for the report. 
Which ios version? Do you use an external keyboard or the smart keyboard?

**Comment by PlanetWilson** [comment]
iOS 9.3.2, not using any keyboard just the on-screen one

**Comment by PlanetWilson** [comment]
Okay narrowed it down a bit more. It happens when pasting in a command from the clipboard. Just typing is fine

**Comment by gogolith** [comment]
Great i'm able reproduce this, now... i'll provide a fix with the next GoCoEdit update. 
Thank you very much.

**Comment by PlanetWilson** [comment]
No problem. Not sure how/where to leave feedback/suggestions but would be great if you could edit files across a network share like SMB/NFS. Thanks!

**Comment by gogolith** [comment]
This should be solved. If not please reopen the issue...
Thank you.
