### ISSUE TITLE
OneDrive for business

### ISSUE THREAD

**Issue by mhotraining** [gogolith/gocoeditserver#115]
Unable to login to onedrive for business.(it's works with onedrive personal)
When i add through "manage remotes + onedrive", the authentication page opens, i add my email account address (OneDrive  for business) and when the page load to enter password the page crash and (kill) close the application.
i tested with ipad pro and ipad classic, same behavior.

**Comment by barryhostead** [comment]
I’m seeing the same... is there any timeline on a fix for this, I bought the app for this integration :-(

**Comment by mhotraining** [comment]
Closed, GREAT

**Comment by ANorwoodD** [comment]
@gogolith I am having a similar issure as above, although I don't see the app crash. I just can't see Onedrive for Business as a connected remote location.

**Comment by rickwalz** [comment]
I am unable to connect to OneDrive pro. I enter my email then a blank white screen pops up and goes away.
