### ISSUE TITLE
Delete key fails from external keyboard

### ISSUE THREAD

**Issue by pioneerwebsites** [gogolith/gocoeditserver#13]
When typing the name of a new remote FTP connection, the delete key does not function.

I've hard restarted the device (iPad Pro 9.3.2) and deleted and reinstalled the app.

**Comment by gogolith** [comment]
Hi,

i can confirm this issue. i will fix it GoCoEdit 9.1.

thank you.

regards
Christoph

**Comment by gogolith** [comment]
This should be solved. If not please reopen the issue...
Thank you.
