### ISSUE TITLE
Doesn't autodetect .cpp files 

### ISSUE THREAD

**Issue by sbowman** [gogolith/gocoeditserver#15]
Seems to autodetect other file types (tried .lua, for example).  But when I open a .cpp file, it defaults to text.  Highlighting works fine if I manually switch to c++, but it doesn't stick.  If I open another .cpp file, I have to manually switch to c++.

Note that .hpp files do open as c++ files.

**Comment by gogolith** [comment]
Hi Sbowman, 

thank you for the report. 
GoCoEdit 11 will fix this issue. 

For GoCoEdit 10 you can use a workaround with a Custom Mode (Extension). 
Simply add a Custom Mode (Settings -> Advanced -> Custom Syntaxmodes)
with this code:

```
{
  "extends":"c++",
  "ext":[
    "cpp"
  ]
}
```

**Comment by sbowman** [comment]
Thanks for the tip.  Workaround worked perfectly.
