### ISSUE TITLE
Lost all data / unable to resume working

### ISSUE THREAD

**Issue by chiragnd** [gogolith/gocoeditserver#16]
This morning, I can no longer work in GoCoEdit with the following issues:
- random popup with no info shows up on the main screen. Cannot dismiss.
- My remote servers have been lost, nor can I add fresh ones to resume working.

Screenshots attached.
![img_0228](https://cloud.githubusercontent.com/assets/1480933/22329238/d1fcadf6-e3d9-11e6-84b7-5b1eb16ff4bb.PNG)

**Comment by gogolith** [comment]
hi chiragnd,
thank you for the report. Do you use the iOS 10.3 beta?

**Comment by chiragnd** [comment]
Hi 

I do yes ... but am quite sure it worked after the upgrade (which happened on Tuesday) and stopped on Thursday but am unsure now that you ask ...

Cd

**Comment by chiragnd** [comment]
@gogolith Hi, do you have an ETA to fix this issue?

**Comment by gogolith** [comment]
I hope for a short review and a release this week

**Comment by chiragnd** [comment]
Hey,

Just got the update which says the bug has been fixed, but not really. Don't see the big box covering anything but still can't add remotes :\
![img_0233](https://cloud.githubusercontent.com/assets/1480933/22895923/9fbc1ad6-f237-11e6-969b-41e1d6820c10.PNG)

**Comment by gogolith** [comment]
next fix is on the way...

Am 13.02.2017 um 18:59 schrieb chiragnd <notifications@github.com<mailto:notifications@github.com>>:


Hey,

Just got the update which says the bug has been fixed, but not really. Don't see the big box covering anything but still can't add remotes :
[img_0233]<https://cloud.githubusercontent.com/assets/1480933/22895923/9fbc1ad6-f237-11e6-969b-41e1d6820c10.PNG>
