### ISSUE TITLE
what's the format of the key for conencting a sftp server should be?

### ISSUE THREAD

**Issue by boistordu** [gogolith/gocoeditserver#18]
is a privatekey from puttygen good? because it doesn t seem to ask me for the password of the key but only the password of the server....

**Comment by boistordu** [comment]
even if I create a key without password it doesn't check it.

**Comment by boistordu** [comment]
actually sftp doesn't work at all even with just a password and a login

**Comment by gogolith** [comment]
Hi boistordu,

does the key work in another app? Can you please provide a screenshot of your connection (remote settings in GoCoEdit) settings to develop@gogolith.de

**Comment by boistordu** [comment]
directly from puttygen and i transfer the file through sync. should I convert it in openssh or ssh.com? 
I m sending you the screenshots now

**Comment by boistordu** [comment]
Okey so it seems that it works with openssh but not the original file of puttygen. So we always need to export.
And it seems that a protected key doesn’t work either? Correct?

De : Christoph Gogolin [mailto:notifications@github.com]
Envoyé : 27 February 2017 21:23
À : gogolith/gocoeditserver <gocoeditserver@noreply.github.com>
Cc : boistordu <padawan440@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [gogolith/gocoeditserver] what's the format of the key for conencting a sftp server should be? (#18)


Hi boistordu,

does the key work in another app? Can you please provide a screenshot of your connection (remote settings in GoCoEdit) settings to develop@gogolith.de<mailto:develop@gogolith.de>

**Comment by chmike** [comment]
I create the key with ssh-keygen on linux and it works fine. It has a passphrase. When I type the pass phrase I can login. Of course I added the public key in authorized-keys. 

The only problem I have is that  I can't remove the private key. I had to change the passphrase and uploaded the private key. I didn't find how to remove the old one. 

It's not convenient to upload the private key to GoCoEdit. Why not supporting sftp to get the private key ? I can't directly access dropbox or icloud from a linux host. The termius iOS app has a convenient method to create and install private keys all by itself.

**Comment by boistordu** [comment]
So the ssh-keygen format have worked it for you ? Strange, I wonder why it won’t for me.

De : Christophe Meessen [mailto:notifications@github.com]
Envoyé : 07 March 2017 21:40
À : gogolith/gocoeditserver <gocoeditserver@noreply.github.com>
Cc : boistordu <padawan440@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [gogolith/gocoeditserver] what's the format of the key for conencting a sftp server should be? (#18)


I create the key with ssh-keygen on linux and it works fine. It has a passphrase. When I type the pass phrase I can login. Of course I added the public key in authorized-keys.

The only problem I have is that I can't remove the private key. I had to change the passphrase and uploaded the private key. I didn't find how to remove the old one.

It's not convenient to upload the private key to GoCoEdit. Why not supporting sftp to get the private key ? I can't directly access dropbox or icloud from a linux host. The termius iOS app has a convenient method to create and install private keys all by itself.

**Comment by chmike** [comment]
You should first try with a regular ssh connection. You should check that ssh is configured to accept authentication with keys. 

```
# Authentication:
LoginGraceTime 120
PermitRootLogin prohibit-password
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
#AuthorizedKeysFile     %h/.ssh/authorized_keys
```
I suggest you also check the name of the authorized-keys file. I have seen some name differences which prevented the public key authentication to work. In my case it's `authorized_keys` with an underscore.

You can test this by trying to reconnect on your own computer with public key. 

This is the command I used to create the keys `ssh-keygen -t rsa -f ~/.ssh/id_rsa_xxx`.  

This is the command I used to add the public key to the authorized_keys file: `cat ~/.ssh/id_rsa_xxx.pub >> ~/.ssh/authorized_keys`.

It's the file ~/.ssh/id_rsa_xxx that I uploaded into GoCoEdit. Unfortunately, GoCoEdit does not provide a safe method to upload the private key in the application it you don't have a pass phrase. You have to copy the file on dropbox or iCloud. GoCoEdit can only get it from these servers. I guess through the apps installed on the device. 

Ideally, GoCoEdit should generate the private and public key locally, and allow to copy/past the public key from GoCoEdit to the target computer. We could use the minishell to do that. In that case a pass phrase less private key is conceivable if GoCoEdit protects it. That would be convenient. Termius does that.

**Comment by gogolith** [comment]
Hi, 
generating keys sounds like a nice feature request... i'll add it to my roadmap. 
In general imported ssh private keys are saved in the local /ssh folder and can be deleted from the file explorer in the local tab. 

You can also add ssh keys with iTunes (file sharing) by drag it to the root folder of GoCoEdit.

**Comment by chmike** [comment]
Thanks @gogolith. I should have seen that. Fixed my certificates.
