### ISSUE TITLE
Keyboard positioning render app unusable

### ISSUE THREAD

**Issue by IPv6** [gogolith/gocoeditserver#19]
After latest update i have an issue with keyboard wich prevents app from being used. Apparently keyboard doesn`t stay at the bottom anymore. It floats to the center of screen, over the text. Hide/show keyboard or reinstall app does not help.

Before this issue arrived i managed to accidentally swipe misterious screen from right side of iPad (ipad2, ios10). May be this is related

**Comment by gogolith** [comment]
Hi,

Sounds like you enabled the split keyboard function in iOS? Please try to hold the hide keyboard button on the lower right to redock your keyboard.

**Comment by IPv6** [comment]
Oh, thank you very much. You are right. This is not a GoCoEdit issue at all.

"you enabled the split keyboard function in iOS" - yep, it was enabled, disabling it helped to solve this problem.
