### ISSUE TITLE
Connection stuff

### ISSUE THREAD

**Issue by mrcrusty12** [gogolith/gocoeditserver#2]
I don't understand how to set up the app to be able to work, if it matters I use Java

**Comment by gogolith** [comment]
Hi mrcrusty12, 

for a initial setup you need to open the sidebar (tab on the top left button) 
go to connections (the book icon on the bottom left) and press the +new button.
Select your servers connection type (Sftp or Ftp).
Enter your servers connection data:
Host Address: (addess of your ftp server) something link "myftp.com"
Username and Password. 
Press save and connect.

**Comment by mrcrusty12** [comment]
What is the server connection? And how do I make a server?
Thanks

**Comment by gogolith** [comment]
in current version the app works remote only.
 ( edit files on your device is possible at version 3 - release in some days)
currently you have to own a server with ftp or sftp access to host your files. 
cheap servers are available e.g. on Amazon Web Services AWS
