### ISSUE TITLE
Google Drive Authentication Fails

### ISSUE THREAD

**Issue by brownlo** [gogolith/gocoeditserver#21]
When attempting to access remote files on Google Drive, authentication fails with the following error:

403
Error: disallowed_useragent

Reported on iPad Pro.

**Comment by gogolith** [comment]
Looks like Google changed the authentication process, nice to know. I'll fix it in the next release ( GoCoEdit 11.2 )
Thank you for the report.

**Comment by lbrow240** [comment]
Hi Christoph,

When is 11.2 slated for release? Unfortunately I'm completely reliant on
remote Google Drive editing, and that's the reason I purchased GoCoEdit.

Let me know, thank you!

Logan

**Comment by gogolith** [comment]
I'll do my best... give me 2-3 Days for a beta release. Please E-Mail me your Apple E-Mail Address for Testflight to develop@gogolith.de

**Comment by lbrow240** [comment]
I've tested the update through Testflight and the remote connection can establish now. One thing of note it that not all of my Google Drive folders appeared in the browser. I was able to get the missing folders to appear by changing the name of the folder in drive and then refreshing the connection. I had to do this for multiple individual folders until they were all accessible through GoCoEdit.

**Comment by gogolith** [comment]
are this some special folder? Do you have a way to reproduce this behaviour?

**Comment by lbrow240** [comment]
These are not special folders, just normal Google Drive folders. 

There are still folders that are not showing up in GoCoEdit at the moment that I can reproduce this with. The interesting behavior is that once I rename a folder and refresh GoCoEdit, once it sees that folder, changing it's name back to what it was does not hide the folder. It's still visible. 

I can't find a correlation between the folders that are experiencing this behavior and ones that are not. They have varying amounts of files within them, from as little as two files to as many as 500 files. They also have varying file types: images, html files, docs, pdfs, etc. Lastly, they have varying creation dates. There's a mix of recently created folders and old folders that do not show up until renamed.

**Comment by gogolith** [comment]
gce 14 should fix this issue... please check that... release soon.

**Comment by brownlo** [comment]
Great. Thank you!
