### ISSUE TITLE
Unable to preview files in the browser...

### ISSUE THREAD

**Issue by rjm449** [gogolith/gocoeditserver#22]
Hi, 
  I just got GoCoEdit on my iPhone SE and am unable to find where to preview my code. I don't see how to open it in Safari or in the internal browser like the options in the settings suggest that I should be able to do.

Here's a link to a picture of the dropdown menu on my iPhone where I thought the PREVIEW option was supposed to be, based on the depiction of it on your website... 
https://gyazo.com/377cf7f14e825003fd32731e386ea7c2

I thought PREVIEW was supposed to be to the right of SHOW MINISHELL but it's not there on mine.

Any ideas?

**Comment by gogolith** [comment]
Hi rjm449, 
I see you open the files direct form external sources. (open from) 
These files are sandboxed by ios within the other application and so gocoedit can't run it with the it's integrated webserver. 
If you want to preview this files you can import it to GoCoEdit ( Tap + -> Import ) or if your external App supports it use open for whole folders. (works with Git2Go, Clone, WorkingCopy, etc.)

**Comment by rjm449** [comment]
Yeah, importing them worked great. 

Thanks so much, gogolith. :) Cool app!
