### ISSUE TITLE
Emacs Orgmode syntax highlighting

### ISSUE THREAD

**Issue by mpeuster** [gogolith/gocoeditserver#23]
Hi,

great iOS testeditor you created there! Not sure if someone is interested in this but I created a sytaxhighlighting definition for Emacs Orgmode file: https://gist.github.com/mpeuster/bce90e9365531e0e4ff3ceb366c6b4e8

Best,
Manuel

**Comment by gogolith** [comment]
Hi Manuel, 
thank you... great. 
Can i post the code on GoCoEdit.com? 
(currently working on an mode and theme download area) 

regards

**Comment by mpeuster** [comment]
Sure. Feel free to use it wherever you like.
