### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by haxblade** [gogolith/gocoeditserver#24]
Hallo!

I've just installed GoCoEdit.  It is overkill for what I need, but so many of the other text/document editors for iOS haven't made updates since years.  However, after connecting GoCoEdit to Dropbox, whenever I launch the app, it immediately returns me to my home screen.  The app appears to still be running in the background, but I can't interact with it or it crashes again.  iPhone 5S, iOS 10.3.3  Dropbox was configured with name = 'docs', initial path = 'docs' (which is an existing folder within the Dropbox folder)

I hope you can help, thank you!

**Comment by gogolith** [comment]
Hi Hexblade,

have you any crash logs? 
Do you have tried to delete and reinstall GCE?

regards

**Comment by gogolith** [comment]
is your problem solved? If not please reopen this issue...
