### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by desduvauchelle** [gogolith/gocoeditserver#25]
Hello.
App seems awesome but I've bought a bunch of apps before and was disappointed. Do u have any sort of video on YouTube or other that shows the UI and functionality a bit better?

While I'm here...Might as well ask my question:
I'm a web developer. I use mongodb, nodejs for server and webpack for builds.
Is it possible for me to ssh to my Mac or raspberry pi and then:
- launch mongodb through a terminal tab
- open a new terminal window, launch webpack,
- launch another terminal ssh and launch my node server...
- And edit my files on the other computer through ssh?

PS I think it's a very common workflow for web developers btw. If u can do this, u should make it more obvious on your landing/sales pages

Thanks Denis

**Comment by gogolith** [comment]
Hi Denis, 
yes its possible. But GoCoEdit does only support multible editor tabs and only one terminal instance. 
You have to use background tasks in your terminal or something like screen. 

Thank you
regards
Christoph
