### ISSUE TITLE
REMOTE SFTP issue

### ISSUE THREAD

**Issue by cipher-dude** [gogolith/gocoeditserver#26]
I have been able to connect to my server via SFTP from GoCoEdit on IPhone without issues. My rsa fingerprint has been changed on my server, so I can't connect now. I've removed the connection and added it back in GoCoEdit, but connection fails. How do I remove the fingerprint for that server in GoCoEdit?

**Comment by gogolith** [comment]
Hi cipher-dude,
GoCoEdit don’t stores or checks the fingerprint at this moment. There must be a different issue.
