### ISSUE TITLE
gcemode file for Julia Language 

### ISSUE THREAD

**Issue by algorithmx** [gogolith/gocoeditserver#27]
Has anyone successfully built the .gcemode file for JuliaLang?

**Comment by algorithmx** [comment]
I tried the following

[Julia2.gcemode.txt](https://github.com/gogolith/gocoeditserver/files/1271970/Julia2.gcemode.txt)

Still cannot parse numbers correctly. I hope a feature of auto bracketing w.r.t. the keyword "end"

**Comment by algorithmx** [comment]
Improved with square bracket matching

[Julia.gcemode.txt](https://github.com/gogolith/gocoeditserver/files/1271984/Julia.gcemode.txt)

**Comment by algorithmx** [comment]
Better version for the gcemode file of JuliaLang
Also gcetheme file

Sorry about my fauvism taste on the coloring ...

[Julia.gcemode.txt](https://github.com/gogolith/gocoeditserver/files/1272450/Julia.gcemode.txt)
[Julia.gcetheme.txt](https://github.com/gogolith/gocoeditserver/files/1272452/Julia.gcetheme.txt)

**Comment by algorithmx** [comment]
How to register the declared functions / variables ?

**Comment by gogolith** [comment]
you mean for the symbol_search?

**Comment by gogolith** [comment]
Can i post the mode and theme at http://gocoedit.com/extensions ?

**Comment by ssehztirom** [comment]
The above mentioned theme throws an error (below) after an GoCoEdit update (unfortunately don’t know which update) and sometimes the buffer window turns white during scrolling when editing Julia scripts.
TypeError: undefined is not an object (evaluating pend.text)

 Do you have an idea what could cause this ?

**Comment by ssehztirom** [comment]
Sorry, not the theme but the mode :)

**Comment by gogolith** [comment]
Hi, thank you for the hint... i'll check that...

**Comment by ssehztirom** [comment]
Thank you very much!

**Comment by ssehztirom** [comment]
Hi it seems as if the latest update has resolved the error (did not experience it since three days).
Thanks!

**Comment by gogolith** [comment]
ok, please keep me informed if it happens again.

**Comment by ssehztirom** [comment]
I now figured out when the bug occurs: in case an “@“ accidentally is followed by a space (“ “): “@ “

Moritz
