### ISSUE TITLE
An example for dash_docsets ?

### ISSUE THREAD

**Issue by algorithmx** [gogolith/gocoeditserver#28]
Hi,
I have downloaded the Dash App and insert the line in the gcemode file. But what and how to trigger within the code editor? I imagine it is possssible to lookup definitions / helps within the GoCoEdit editor, just like in Pythonista ?

**Comment by gogolith** [comment]
Hi, 
GoCoEdit integrates the Dash URL sheme. (https://kapeli.com/dash_plugins)
example: dash-plugin://keys=python,django&query=string
Keys are the dash_docsets in your gcemode file. The query is the current selection in the editor. 
You can trigger a search in dash by tapping the one of the selection markers.
