### ISSUE TITLE
“ VS "

### ISSUE THREAD

**Issue by beaudry213** [gogolith/gocoeditserver#29]
I want to use this app for writing Java Programs. I’m using an external keyboard with my iPad and when I try to type a double quotation mark, like this vertical one ", it instead inputs a slanted one “, which will not do for java. Since the slanted double quote has a different Unicode value from the vertical one, when I try to declare a string it outputs an error. For example:

public class HelloWorld {
	public static void main(String[] args){
		
		System.out.println(“HelloWorld”);
	}
}

When compiled this code outputs these two errors regarding the quotations:
Javac HelloWorld.java

HelloWorld.java:4: error: illegal character: ‘\u201c’
        System.out.println(“HelloWorld”);
                                        ^
HelloWorld.java.4: error: illegal character:’\u201d’

I am aware of the black tab at the bottom of the screen that has the correct type of quotation mark, but because I’m using an external keyboard this is very inconvenient. I tried to make use of custom text replacements in the settings of my iPad, so that it would replace my incorrect quotations with the correct one but this didn’t work because it has to be padded by white space for the text replacements to work.

**Comment by gogolith** [comment]
Hi beaudry213,

This is a new iOS 11 feature called smart Punctuation. 
I not able to disable it the replacement for GoCoEdit until iOS 11 is official released.
But you can disable it in your iOS Settings globally. 
Go to Settings -> General -> Keyboards and disable the Smart Punctuation feature. 

Thank you 

regards
Christoph
