### ISSUE TITLE
SSH (Minishell) not working.

### ISSUE THREAD

**Issue by iammarkoradak** [gogolith/gocoeditserver#3]
Amazing app, congrats. Finally a decent editor for iOS devices. 
I do have a problem with it though - minishell get's stuck at connecting. I've tried both iPad Air, and iPad 4, as well as multiple iPhones. I also tried multiple servers...

Any suggestions?

**Comment by nikolakanacki** [comment]
Same here. Stuck at the same step, never hit the server. Tested on both iPad and iPhone.

**Comment by gogolith** [comment]
Hi, are you nikolakanacki, iammarkoradak trying to connect to the same server? 
What is your connection config? 
On which port?
Con you connect from a desktop Terminal app via ssh user@yourserver.com

**Comment by iammarkoradak** [comment]
We're connecting to an IP address, so THSR might be a problem..?

So it's user@xxx.xxx.xx.xxx using the port 1307. Terminal nad gde other apps are working without any problems.

I've also tried SSHing into my Mac, using the default port, without any luck. Again user@ip...

Thanks,
Marko

**Comment by gogolith** [comment]
ok thanks for the fast answer... 
what are you typing into the HOST field? user@ip? oder ip only?

**Comment by iammarkoradak** [comment]
IP only. Though I just tried with user@ip as well, but with same results - stuck at connecting...

**Comment by gogolith** [comment]
I found a possible problem on using a non standard port... 
I fixed it and created an UI update... 
Please go in GoCoEdit -> Settings -> UPDATE NOW (wait a few minutes if it does not appears) 
then try it again.

**Comment by iammarkoradak** [comment]
Yeah, that was the problem. It connects straight away now.

Thanks :)

**Comment by nikolakanacki** [comment]
Sorry for the delay. Yes, that did it! Great app btw :)

**Comment by gogolith** [comment]
Thank you for the report. I currently working on web-presence where you can send suggestions. But that might take some time.
At now please submit suggestions to develop@gogolith.de

Btw GoCoEdit Version 4.0 is ready and at now on apple review. 
It will be released in some days.
