### ISSUE TITLE
Parentheses and Quotes changing character

### ISSUE THREAD

**Issue by Ben-Lichtman** [gogolith/gocoeditserver#30]
Maybe this is a new IOS 11 thing? I’m not sure. But it seem that now when I am trying to write strings the single and double quotes are being automatically changed into the Unicode quotes (with the upward and downward strokes) which is breaking the syntax highlighting.

I am using a Bluetooth keyboard on IOS 11

**Comment by gogolith** [comment]
Hi Ben, i think this is a Duplicate of #29 
right?

**Comment by Ben-Lichtman** [comment]
Oh yes. That's right.
