### ISSUE TITLE
onedrive logon does not recognise account

### ISSUE THREAD

**Issue by strannik19** [gogolith/gocoeditserver#31]
Trying to logon with my work Office 365 account to access OneDrive, but the logon screen that gocoedit displays says that my account cannot be found. OneDrive app itself works fine with my logon.

**Comment by gogolith** [comment]
Hi Strannik19, 
Sorry, only personal OneDrive Accounts are supported at this time. Office 365 / Business OneDrive support will be available soon. 
Thank you.
