### ISSUE TITLE
Currently supported syntax .gcemode files

### ISSUE THREAD

**Issue by nate** [gogolith/gocoeditserver#32]
Could you publish the gcemode files for currently supported syntaxes? I'm having trouble understanding the format and I was hoping to look at Markdown's. I'm trying to make a gcemode for org-mode.

Thanks!

**Comment by nate** [comment]
Or if you have any other suggestions for figuring it out...

**Comment by nate** [comment]
Looks like https://github.com/gogolith/gocoeditserver/issues/23 gets me part of the way there, but it's not handling things like lists or definition lists.

**Comment by gogolith** [comment]
Hi Nate, 

here is another example: 
http://gocoedit.com/extensions/modes

The integrated modes are currently not based on the gcemode syntax. They are developed before gce supports gcmode files. 

Org Mode looks very complex and i don't know if all features are mappable to a gcemode.

**Comment by nate** [comment]
It's fairly complex but the basic features are similar to markdown. RBB Rapid really isn't a very complex syntax and so it's not a very good example. I suspect markdown syntax is parsed with another type of syntax highlighter?

**Comment by gogolith** [comment]
yes there is a custom coded class for parsing markdown in gce. 
Apple does not allow to reload user generated or downloaded code on runtime. 
This why i have to use the JSCore Sandboxing and these config like syntax for gcemodes.
