### ISSUE TITLE
regex system

### ISSUE THREAD

**Issue by nate** [gogolith/gocoeditserver#33]
which regex system is used for .gcemode files? I'm getting some weird behaviors...

**Comment by gogolith** [comment]
Hi Nate, 

can you give me an example for the wire behaviors? 
The regex syntax is parsed line by line with JSCore.

**Comment by nate** [comment]
JSCore? Do you have a link to it? I'd like to play with it locally to understand its capture groups.

My specific issue was I was using positive lookahead in a regex with multiple capture groups where one of the capture groups was within the positive lookahead. It was dropping the trailing character for some reason...

Anyways, I stopped using positive look ahead and it seems to work ok now.

One thing I'd love to be supported are empty capture groups. For example, for [orgfile header syntax](http://orgmode.org/worg/dev/org-syntax.html#Headlines_and_Sections) syntax I would love to use the following:

```json
{
    "state": "start",
    "parse": [{
        "token": ["atom", "string", "atom", "string", "atom"],
        "regex": "(\\*+)(?: +(TODO|DONE))?(?: +(\\[#[A-C]\\]))?(?: +([^\\n]+?))?(?: +((?::[a-zA-Z0-9@#%]+)+:))? *$",
        "strictregex": true,
        "onlyOnLineStart": true
    }]
}
```

It gives me an error when I do because any one of the capture groups can be missing. Instead I have to do this complex solution:

```json
{
    "name": "orgfile",
    "ext": [
        "org", "ORG", "Org",
    ],
    "dash_docsets": "",
    "tokenizer": [{
            "state": "start",
            "parse": [{
                "token": "variable-2",
                "regex": "\\*+ +",
                "onlyOnLineStart": true,
                "stateAfterMatch": "heading"
            }]
        },
        {
            "state": "heading",
            "parse": [{
                    "token": "def",
                    "regex": "^(TODO|DONE) *",
                    "strictregex": true,
                    "stateAfterMatch": "heading"
                },
                {
                    "token": "attribute",
                    "regex": "^ *\\[#[A-Z]\\] *",
                    "strictregex": true,
                    "stateAfterMatch": "heading"
                },
                {
                    "token": ["variable-2", "tag"],
                    "regex": "^([^\\n]+?)((?::[a-z0-9@#%]+)+:) *",
                    "stateAfterMatch": "start"
                },
                {
                    "token": "tag",
                    "regex": "^(:[a-z0-9@#%]+)+: *",
                    "stateAfterMatch": "start"
                },
                {
                    "token": "variable-2",
                    "regex": "^[^\\n]*",
                    "stateAfterMatch": "start"
                },

            ]
        }
    ],
    "hint": {},
    "symbol_search": {
        "regex": [
            "TODO\\s{1,}\\w{1,}",
            "DONE\\s{1,}\\w{1,}",
        ]
    }
}
```

**Comment by nate** [comment]
Ok, here's an example of weird behavior. Using the above regex it no longer gives me an error but it *does* break on highlighting and I can't be sure why....

[Image1.png](https://s3.amazonaws.com/monosnap.sutton.me/20171009154136-Image.png)
[Image2.png](https://s3.amazonaws.com/monosnap.sutton.me/20171009154211-Image.png)

This despite it working in [every available type on regex101](https://regex101.com/r/UU11ZA/1).

**Comment by gogolith** [comment]
Hi, 
thank you for the great engagement. 
JSCore is a Javascript Sandbox on iOS. That means JS compatible regex should work. 

Using token params with an array is currently not supported. Sorry you have to use the complex solution at this moment.

**Comment by nate** [comment]
The manual suggests that it *is* supported... http://gocoedit.com/docs/custommodes

```It's' possible to pass an array of tokens to match multible capture groups at once.
"regex" : "(function)(\\s+)([\\w]*)", "token" : ["keyword",null,"variable"]```

**Comment by nate** [comment]
Is there a way to match the end of a line?

**Comment by gogolith** [comment]
you are right sorry my failure... this feature was not final. 
I'll remove it from the manual. 
you can match a line end with ".*$" on the last position of your parse array.

**Comment by nate** [comment]
Is that the end of the file or the end of the line? I guess this gets to the heart of how the syntax highlighter works. Does it work line by line? Or does it operate on the entire file as one string?

**Comment by nate** [comment]
Like, does it take a line, start at the "start" state, match all it can, then get the next line, start at the start state, match all it can, over and over?

**Comment by gogolith** [comment]
This is the end of the line. 
The Highlighter works line by line but keeps its state over multiple lines. 
It will start with the start state and parses the "parse" array tokens until a regex matches. 
Each object can decide what to do after a regex is matched and stay in the current state or switch to another. (stateAfterMatch, overwriteState and recoverState) 
This state will used on the next line as the initial state. 

To revert the state to the start state on a line end you can do something like:

"parse": [{
                    "token": "def",
                    "regex": "^(TODO|DONE) *",
                    "strictregex": true,
                    "stateAfterMatch": "heading"
                },
                {
                    "token": "attribute",
                    "regex": "^ *\\[#[A-Z]\\] *",
                    "strictregex": true,
                    "stateAfterMatch": "heading"
                },
                {
//null or something else but not a predefined token 
                    "token": "null", 
                    "regex": ".*$",
                    "stateAfterMatch": "start"
                }
            ]
