### ISSUE TITLE
GoCoEdit returns me to home screen when I open it on my iPhone (Dropbox initial directory issue?)

### ISSUE THREAD

**Issue by MarshallBuhl** [gogolith/gocoeditserver#35]
Hi,

I just installed GoCoEit on both my iPad (iOS 11.0.1) and my iPhone 7 (iOS 10.3.3).   It worked fine on my iPad, but not my iPhone.  A user named haxblade reported the exact same problem I had on Aug 11 (Crash on open #24).  It doesn't actually crash, but returns me to the home screen.  This did not happen until I connected it to Dropbox.  You asked him if he had "any crash logs" or if he had "tried to delete and reinstall GCE."  I don't know where crash logs are on the iPhone, but I did try reinstalling it.  It worked fine after reconnecting it to Dropbox.  One thing I did differently was that I did not specify an initial directory the second time on the iPhone.  I did not do it the first time on the iPad and it worked fine then.

So, I suspect that it might have something to do with specifying an initial directory.

**Comment by gogolith** [comment]
Hi MarshallBuhl, 

thank you for this infos... i tried a bit around and find a possible crash with the new Dropbox 2 SDK. 
I happens only if your Dropbox initial directory not starts with a slash. 
p.e.
/myfolder/ (works) 
myfolder/ (crash) 
Can you confirm?
 I'll fix this soon...

Thank you!

**Comment by gogolith** [comment]
This should be solved with GoCoEdit 12.1. 
Can you confirm?

**Comment by gogolith** [comment]
if not please reopen.
