### ISSUE TITLE
ES Modules dose not work

### ISSUE THREAD

**Issue by Latel88** [gogolith/gocoeditserver#36]

**Comment by Latel88** [comment]
Do not read js file with module specified as script tag in internal browser and preview of external browser.

**Comment by gogolith** [comment]
Hi Latel88, 

Thank you for the report.
Can you please provide an example or a short step by step description to help me to reproduce your issue.

**Comment by Latel88** [comment]
[main.js]
import text from "./text.js";
console.log( text );

[text.js]
export default "Hello World";

[index.html]
<!doctype html>
<html>
<head>
	<script src="./main.js" type="module"></script>
</head>
</html>

1. Prepare the above three files.
2. Open "index.html" and "Preview"
3. If "Hello World" is displayed in "Console", it works.

For the specification of esmodule please see the URL below.
[Attributes->type->module]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by gogolith** [comment]
Great. I've found a reason for this issue in the internal web server. It delivers a wrong mime type for js files. I'll fix it in the next release. 
Thank you very much!

**Comment by gogolith** [comment]
Should be fixed in GCE >= 13. If not please reopen... Thank you.
