### ISSUE TITLE
All files like folders

### ISSUE THREAD

**Issue by jlbhfantasma** [gogolith/gocoeditserver#37]
Hi, i had bought your software today, i connect to ftp and i try to open a txt, html, php or asp file but when i clic every file software show me another similar file and i can not open, looks like software convert every file in folder.  Please see 2 images attached
![d3030540-8a2f-4a78-8490-2358841a4ec4](https://user-images.githubusercontent.com/33561213/32684545-8118ec90-c652-11e7-8c8b-76eec281ea9c.png)

![dd0201a6-69a6-4322-88e2-88974f7047a3](https://user-images.githubusercontent.com/33561213/32684531-53ed2452-c652-11e7-9793-4b89997d3f32.png)

Could you help me please, thanks.

IPAD AIR 1

**Comment by gogolith** [comment]
Hi jlbhfantasma, 

thank you for this report... this looks like a problem with your ftp server. 
GoCoEdit displays all files like symlinks. Does it works work with other ftp tools (p.e. Documents app)

Can you give me some information about your ftp server / setup or your hoster? 

Thanks

**Comment by jlbhfantasma** [comment]
hi, windows server 2012 r2,  i use filezilla, cyber duck and it works.  i have bought ftp client pro and it works.

**Comment by gogolith** [comment]
Thank you for the feedback, i'll try to realize a similar setup and try it out...

**Comment by gogolith** [comment]
Should be fixed since release 12.3. else reopen this issue please. 
Thank you.
