### ISSUE TITLE
cannot open text files over sftp

### ISSUE THREAD

**Issue by mhalabi1981** [gogolith/gocoeditserver#38]
hello it appears that there is limit on file size when attempting to open txt files over sftp can that be altered? i have file with size 30 or 40mb that the app refuses to open

**Comment by gogolith** [comment]
Hi mhalabi1981, 

thank you for your request. 
Currently the file limit can't altered because auf stability issues. 
But i will add an "on your own risk option" in the next release. (Gce >= 12.3)

Thanks
regards

**Comment by mhalabi1981** [comment]
Awesome thank u this is a great app
