### ISSUE TITLE
Run and compile code?

### ISSUE THREAD

**Issue by Jaimeclaure** [gogolith/gocoeditserver#4]
I need to know if between the qualities of your application is the code compiled languages ​​like C, C ++, Java, Swift and what other languages ​​that can run code and compile.

**Comment by gogolith** [comment]
hi jaime,
currently there is no way to compile code because apple dont allow it in applications where you can import and export files. 
But GoCoEdit supports syntax highlighting for this languages and export to Icloud, dropbox and ftp or sftp servers.
