### ISSUE TITLE
iCloud Drive support?

### ISSUE THREAD

**Issue by shinypb** [gogolith/gocoeditserver#41]
Any chance of getting first-class iCloud Drive support, e.g. making it work like Dropbox or Google Drive do?

**Comment by gogolith** [comment]
Hi shinypb, 
Thank you for you request. 

Can you describe a bit more detailed how this should work and what is the benefit of the current iCloud implementation. 
You can currently open files or whole folder with the open from function from your iCloud Drive or Files App. On the other side you have a iCloud folder (on local root level) for sharing your files.

Here a short example Video
[http://gocoedit.com/video/gce12_external_files_folders.m4v](url)

regards
Christoph

**Comment by shinypb** [comment]
Ah! I didn't have any luck figuring out how to open an entire folder — I must've missed something, and I will try again.

My ideal implementation of this would be for my iCloud Drive to show up in the sidebar just like an SFTP server does, with your custom folder tree component running the show. Perhaps that isn't possible on iOS, though.

**Comment by shinypb** [comment]
Ah, the "open from" function was the missing piece for me. I had expected iCloud Drive to just always be visible in the sidebar or something along those lines, but this works just fine. Thanks for the explanation.
