### ISSUE TITLE
Bug: Disabling auto-keyboard blocks all keyboard input

### ISSUE THREAD

**Issue by shinypb** [gogolith/gocoeditserver#42]
If I set "Enable Auto-keyboard" to false, typing anything at all no longer works — I can't even use the arrow keys to move the cursor around. Turning "Enable Auto-keyboard" back on fixes the problem. 

I can reproduce this 100% of the time, and would be happy to make a screencast if that's useful, although you wouldn't be able to tell when I am hitting keys on my keyboard. 😄)

I'm on a 10.5" iPad Pro with a Smart Keyboard attached.

**Comment by gogolith** [comment]
Hi shinypb, 

If you disable the Auto Keyboard feature GoCoEdit switches to something like a reading mode. That means it only enables Keyboard input by pressing the Keyboard button on the lower right.

**Comment by shinypb** [comment]
Ah, OK. That seems like a very surprising label for that feature — what if we called it "Read-only mode" instead?

What I was actually trying to do was get that strip of special keys across the bottom of the screen to go away entirely. I use an external keyboard, so this is just a waste of screen space for me. Is there a way to do that?

**Comment by gogolith** [comment]
right, buts ist really a read only mode... you can access the keyboard by pressing the keyboard button... its more an no autofocus mode. I'm open for better wordings ;) 

I can't clean determine if there is a hardware or software keyboard in the iOS Sdk but an option could be a good compromise it think.
