### ISSUE TITLE
Feature request: split-screen terminal

### ISSUE THREAD

**Issue by shinypb** [gogolith/gocoeditserver#43]
It'd be great if I could keep a terminal on-screen while I work (e.g. while working on unit tests). Being able to have a terminal at the bottom or on the right would be enormously helpful. :pray:

PS: Keep up the good work! GoCoEdit is wonderful.

**Comment by gogolith** [comment]
Hi shinypb, 

thank you for your request. 
Why do you not use the system Split-Screen Multitasking?

**Comment by shinypb** [comment]
A few reasons:

1. I have the 10.5" iPad, so split screen is too small to get much done. Hence, I'd like a horizontal split, with the terminal across the bottom of my screen.
2. I'd like to keep my SSH set up in GoCoEdit and not need to maintain it in some other terminal app as well.

**Comment by gogolith** [comment]
ok, 
i'll notice this on the possible feature list for the next mayor release. 
Thank you.

**Comment by hibanastudio** [comment]
I’m not understanding something. So the interpreted shell is a terminal? Or do I have to get another app for the terminal and use Gocoedit for ssh.

**Comment by gogolith** [comment]
Hi hibanastudio, gocoedit has a Shell or Terminal called Minishell. 
That means there is ssh command input interface within GoCoEdit. ;) 
You need another machine like a mac/unix pc you can ssh to...

**Comment by hibanastudio** [comment]
Cool!
Thanks for letting me know 😊
