### ISSUE TITLE
FTP connection showing two instances of the same file

### ISSUE THREAD

**Issue by iostester1** [gogolith/gocoeditserver#45]
When connecting to a FTP site and I click on a file with an .ASPX extension, it's displayed twice and I have no way to view it in the code editor.

![screenshot](https://user-images.githubusercontent.com/35231283/34682301-2195cf00-f464-11e7-9c44-38596dcc1cce.jpeg)

Message me and I can provide FTP access; this seems to be only happening on Windows FTP servers.

**Comment by gogolith** [comment]
Hi Tester, 
Thank you for your report...
Yes there is still a problem with some windows ftp servers. 
If you have any ftp credentials for testing reason please mail me. 
develop@gogolith.de
Thank you very much.

**Comment by gogolith** [comment]
Got it, thank you very much... 
The Fix will be available with the next release.

**Comment by iostester1** [comment]
Awesome - thank you!


________________________________
