### ISSUE TITLE
connection problem to ftp

### ISSUE THREAD

**Issue by boistordu** [gogolith/gocoeditserver#5]
Hi, 
I don't succeed to connect to my ftp server. not a firewall problem obviously because I've tried also from inside the network.

it shows me all the time the username and password window but there are correct so I don't understand.

**Comment by gogolith** [comment]
Hi, 
did you used the connector (remote php to ftp) or a normal ftp connection?

**Comment by boistordu** [comment]
A normal ftp connection with another soft works but not with your soft if I try.  I don't know how your soft works so I Don't know if it is a normal ftp connection or not in your soft. 
Le 28 août 2015 8:53 AM, Christoph Gogolin <notifications@github.com> a écrit :Hi, 
did you used the connector (remote php to ftp) or a normal ftp connection?

**Comment by gogolith** [comment]
sorry, i mean did you used the gocoeditserver.php from this git repo?
else it is a normal connection.
sou used the default port or a custom one? 
Any way to reproduce this on my side? Is it possible to create a demo ftp account for a test? 
thank you!

**Comment by boistordu** [comment]
We can every test you want :)

So the ftp connection work with another app in the iPad.  I ve tried to install the connector but I did not succeed for now.  So I ve created a normal connection with the new button and it didn't work.  It was on specific port yes with the vsftpd server.


Envoyé avec Outlook pour Android





On Fri, Aug 28, 2015 at 11:36 AM -0700, "Christoph Gogolin" <notifications@github.com> wrote:
sorry, i mean did you used the gocoeditserver.php from this git repo?
else it is a normal connection.
sou used the default port or a custom one?
Any way to reproduce this on my side? Is it possible to create a demo ftp account for a test?
thank you!

---

**Comment by gogolith** [comment]
ok, i can reproduce it now... its a problem with the ftp framework within GoCoEdit. It ignores some custom ports. An Update is on the way (version 6.0 - release is with iOS9 in the next two weeks). 
A workaround for now is to configure your ftp server to use port 21 for ftp... 
Thank you for the report.

**Comment by boistordu** [comment]
okey thank you for your help :)

Envoyé à partir d'Outlook




On Mon, Aug 31, 2015 at 1:59 AM -0700, "Christoph Gogolin" <notifications@github.com> wrote:
ok, i can reproduce it now... its a problem with the ftp framework within GoCoEdit. It ignores some custom ports. An Update is on the way (version 6.0 - release is with iOS9 in the next two weeks).
A workaround for now is to configure your ftp server to use port 21 for ftp...
Thank you for the report.

---
