### ISSUE TITLE
Text color bug

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [gogolith/gocoeditserver#50]
In Javascript code "(" and ")" or "{" and "}" are originally displayed as pairs, but if these two lines are separated by more than 100 lines, it will be recognized that they are not paired.

**Comment by gogolith** [comment]
hi HIBIKI-CUBE, yes that's correct. GCE renders online 100 lines to keep it fast and smooth. (also on older devices) It's planed to increase the line count in the future. (after dropping the old device support)

**Comment by HIBIKI-CUBE** [comment]
I see.
