### ISSUE TITLE
Cannot use delete key

### ISSUE THREAD

**Issue by ttk-comb** [gogolith/gocoeditserver#51]
I usually use bluetooth keyboard with this app.
However I can't use Delete(Fn+Backspace).
It's unusefull.

**Comment by gogolith** [comment]
Thank you for your issue, i'll check that... 
regards

**Comment by gogolith** [comment]
Next release should add the function...

**Comment by ttk-comb** [comment]
Awesome sauce!

**Comment by ttk-comb** [comment]
I've checked the issue has been fixed and the delete key is now working! Thanks.
 Good job!!
