### ISSUE TITLE
Cannot login to Dropbox

### ISSUE THREAD

**Issue by pauljrob** [gogolith/gocoeditserver#53]
The Dropbox connection works but it never really connects via the App. I auth to Dropbox but then that's it. Any tips?

**Comment by gogolith** [comment]
Hi pauljrob, can you describe a bit more what happens when you create a new dropbox remote. Or can you do a short screencast and send it to develop@gogolith.de
Thank you.

**Comment by gogolith** [comment]
does it work for you, now? if not please reopen...
