### ISSUE TITLE
Regex for multi-line TODO won't work

### ISSUE THREAD

**Issue by carlossierra311** [gogolith/gocoeditserver#54]
Hi Christoph, 
I am trying to add my own token for TODOs in my custom defined syntax mode. My custom syntax mode works well for all my tokens, except for this one. Here is the regex I'm trying to use: 
`TODO:[\\s\\S]*;`

Here is some sample text (split over two different lines) that it won't parse correctly: 
```
TODO: Fecha Proyectada = Fecha de Actualización de la Orden + 
						 ( Amortiguador * ( 1 - Prioridad de la Orden ));
```
This gets parsed (and highlighted) properly though: 
```
TODO: Fecha Proyectada = Fecha de Actualización de la Orden +  ( Amortiguador * ( 1 - Prioridad de la Orden ));
```
I have validated this regex [here](https://regexr.com/3q5oc), and it works as expected. So, is this a bug?
Thanks

**Comment by carlossierra311** [comment]
@mikeMikeymike The regex is part of the ruleset that a custom syntax mode needs in order to find specific tokens inside your code files, and highlight them.  You can find more information about it [here](http://gocoedit.com/docs/custommodes).

**Comment by mikeMikeymike** [comment]
Ahh, thanks.
However, the webpage for GoCoEdit promises that you can search with regular expressions. I paid for the app, but I can’t find it.

**Comment by gogolith** [comment]
Find by regex
You can enter a regular expression in the find field. (loupe icon on the top bar) 
Simply put your search term in Slashes 
p.e.: /my.*word(s)?/

**Comment by gogolith** [comment]
@carlossierra311 
GoCoEdit parses all line by line that means if you want to want to parse over multible lines you have to switch the state.
example:
```
[
  {
    "state": "start",
    "parse": [
      "token": "comment",
      "regex": "\\/\\*",
      "stateAfterMatch": "comment"
    ]
  },
  {
    "state": "comment",
    "parse": [
    ...
    ]
  }
]

```

**Comment by carlossierra311** [comment]
Thank you Christoph. 

In case anyone who ends up here is interested in how I fixed it, here is my final version of the custom syntax mode that recognizes multiple-line TODOs:

```
{	
	"state":"start",
	"parse":[
		...
		{
			"token":"attribute",
			"regex":"TODO: [\\s\\S]*;"
		},
		{
			"token":"attribute",
			"regex":"TODO: [\\s\\S]*",
			"stateAfterMatch":"comment"
		}
	]
},
{
	"state":"comment",
	"parse":[
		{
			"token":"attribute",
			"regex":"[\\s\\S]*;",
			"stateAfterMatch":"start"
		},
		{
			"token":"attribute",
			"regex":"[\\s\\S]*",
			"stateAfterMatch":"comment"
		}
	]
}
```

**Comment by gogolith** [comment]
thanks
