### ISSUE TITLE
Can’t connect to any SFTP Server

### ISSUE THREAD

**Issue by zduffy** [gogolith/gocoeditserver#56]
Hello,

Upon trying to connect to any of my web servers, I received the following error:

Failed establishing socket connection 

I have tried connecting with my domain names and well as IP addresses. I have used GoCoEdit in the past with these servers that have connected previously, so I’m not sure what the issue is. I can connect just fine on my desktop.

**Comment by sqlsolver** [comment]
Same error today. I can connect via SSH using Terminus on iPad.

**Comment by zduffy** [comment]
Like sqlsolver has described, I can connect just find through a different app.

**Comment by gogolith** [comment]
any chance for me to reproduce this? 
Can you create a test account on your not working server? 
If yes please mail me credentials to develop@gogolith.de

**Comment by gogolith** [comment]
Any progress at this issue? Solved? if not please reopen...
