### ISSUE TITLE
Escaping backtick (grave accent in snippets

### ISSUE THREAD

**Issue by icevans** [gogolith/gocoeditserver#57]
I was going to create a snippet for creating Markdown codeblocks. This throws an "invalid snippet data": `"content": "```"`, but I believe is a valid ES6 string literal. (Interestingly, `"`"` works just fine... perhaps whatever is doing the parsing of the snippet template is incorrectly interpreting the double backtick inside the quotes as starting a new template literal?)

So I tried using a template literal: ``"content": \`\`\` ``. But this also throws an "invalid snippet data", but I believe this is a [valid ES6 template literal](http://exploringjs.com/es6/ch_template-literals.html#_escaping-in-template-literals). (Interestingly, `` \` `` doesn't throw the error, but when this snippet is used the `\` character is output along with the `` ` ``, which I believe to be incorrect.)

So it seems to me that there is some sort of bug with the way string and template literals are being processed? Or perhaps I'm just doing something wrong, I'm not super familiar with this syntax.

**Comment by gogolith** [comment]
you are right, i'll check that.. thank you.

**Comment by gogolith** [comment]
next release should solve it....

**Comment by icevans** [comment]
Cool!

**Comment by gogolith** [comment]
can you confirm? is it fixed for your case?

**Comment by icevans** [comment]
Thanks for following up! I can't confirm at the moment because I shattered my iPad screen, but once I get a replacement part and do the fix, I'll follow up with you.

**Comment by gogolith** [comment]
Should work in gce 13.3.x... if not please reopen...
