### ISSUE TITLE
Unable to preview Web page with iOS 12

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [gogolith/gocoeditserver#60]
Hi.
I've used the latest version of app with iOS12 Public Beta 2 and 3.
In this environment, I can't use preview feature neither In-app nor Safari.
Regards.

**Comment by gogolith** [comment]
Thank you... update is on the way. 13.3.6

**Comment by HIBIKI-CUBE** [comment]
The issue fixed and Preview feature is  working well!
Thanks.
