### ISSUE TITLE
Crash on Typing in Preview JS console

### ISSUE THREAD

**Issue by Osmiogrzesznik** [gogolith/gocoeditserver#62]
Good Evening,

I would like to report a bug which started occurring today.

[https://youtu.be/TDnZBcOAe1U]()
as per description, app started crashing on any attempt to type in preview javascript console, even after reinstalling and trying different files.
started: around 29 Aug 2018
phone : iphone 6
ios: 11.4.1

**Comment by gogolith** [comment]
fixed in gce 13.3.x
