### ISSUE TITLE
Last few lines of file hidden by keyboard bar

### ISSUE THREAD

**Issue by robinsiebler** [gogolith/gocoeditserver#7]
The last few lines of a large file are hidden by the keyboard bar. I can scroll up and down to see the lines, but if I try to edit the lines, I cannot actually see them.

Link to video of issue - https://www.dropbox.com/s/199iztlnrd2y9jh/File%20May%2021%2C%2011%2058%2046%20AM.mov?dl=0

**Comment by gogolith** [comment]
Hi Robin,

thank you for this issue report but the Dropbox link throws an error 429.
Can you provide some more informations about your setup? (ios version, device, filesize, highlighting mode).

Thank you.

**Comment by robinsiebler** [comment]
I'll try to figure out why the link is broken. I did a copy/paste, so it should be correct. I am using an iPad Air 2, iOS 8.4.1, filesize is 8kb. Highlighing mode is Python.

On Sun, May 22, 2016 at 12:31 PM, Christoph Gogolin <notifications@github.com> wrote:
Hi Robin,

thank you for this issue report but the Dropbox link throws an error 429.
Can you provide some more informations about your setup? (ios version, device, filesize, highlighting mode).

Thank you.

**Comment by robinsiebler** [comment]
Here is a new link to the video - https://app.box.com/s/m49s0wa3amyh27d7xhc3l1cjrpr79ro7

**Comment by gogolith** [comment]
Thank you robin, i'll try to reproduce this issue.

**Comment by gogolith** [comment]
Hi Robin, your problem should be solved since the latest update. (8.3+)
Can you confirm this?

**Comment by gogolith** [comment]
This should be solved. If not please reopen the issue...
Thank you.
