### ISSUE TITLE
Custom Syntax -- Case Sensitivity for Regular Expressions

### ISSUE THREAD

**Issue by LittleHouse75** [gogolith/gocoeditserver#9]
Hello,

I was attempting to try my hand at writing a custom syntax for the Fountain Screenwriting spec (http://fountain.io).  However, it seems regular expressions for custom syntaxes are currently case INsensitive.  That is [A-Z] is the same as [a-z].

Would you be able you confirm?

Thanks!

-Tim

**Comment by gogolith** [comment]
Hi Tim,

yes this correct. 
I'll add an option in the next release. 

thanks

**Comment by gogolith** [comment]
GoCoEdit 8.4 has a new setting for case sensitive regex: 
"strictregex":true
here is an example mode: 
http://gocoedit.com/ext/modes/rbbrapid.gcemode

Thank you...
